from enum import Enum


class ErrorCode(str, Enum):
    # Auth & User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    WRONG_LOGIN = "AUTH_LOGIN_INVALID"
    WRONG_PASSWORD = "AUTH_PASSWORD_INVALID"
    EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED"
    EMAIL_ALREADY_VERIFIED = "AUTH_EMAIL_ALREADY_VERIFIED"
    EMAIL_TAKEN = "REGISTER_EMAIL_TAKEN"
    USERNAME_TAKEN = "REGISTER_USERNAME_TAKEN"
    ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED"
    ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID"
    TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    TOKEN_MISSING_EXP = "ACCESS_TOKEN_MISSING_EXP"
    TOKEN_REVOKE_FAILED = "ACCESS_TOKEN_REVOKE_FAILED"

    # Shipments
    SHIPMENT_NOT_FOUND = "SHIPMENT_NOT_FOUND"
    SHIPMENT_INVALID_DATE = "SHIPMENT_INVALID_DATE"
    SHIPMENT_INVALID_STATUS_UPDATE = "SHIPMENT_INVALID_STATUS_UPDATE"
    SHIPMENT_SELF_PURCHASE = "SHIPMENT_SELF_PURCHASE"

    # General
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"